version: "3.4"
services:
  service:
    build:
      context: .
      target: development
    ports:
      - "2000:2000" # development
      - "9229:9229" # profiler
    working_dir: &PROJECT_ROOT_DIR /app
    # linux permissions: we must explicitly run as the node user
    user: node
    volumes:
      # mount working directory
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      # the container’s view is authoritative (permit delays before updates on the container appear in the host)
      - .:/app:delegated

    environment:
      # You may set these in the .gitignored local .env file
      # See .env.sample
      DOMAIN: ${DOMAIN}
      PROXY_MODE: ${PROXY_MODE}
      DB_TOKEN: ${DB_TOKEN}
      PUBLIC_CONTACT_EMAIL: ${PUBLIC_CONTACT_EMAIL}
      GAGS_USERNAME: ${GAGS_USERNAME}
      GAGS_PASSWORD: ${GAGS_PASSWORD}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME}
      SESSION_COOKIE_SECRET: ${SESSION_COOKIE_SECRET}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION_TIME_MINUTES: ${TOKEN_EXPIRATION_TIME_MINUTES}
      TOKEN_COOKIE_NAME: ${TOKEN_COOKIE_NAME}
      APP_USER_AGENT_STRING: ${APP_USER_AGENT_STRING}
      SOCKET_ALLOWED_ORIGINS: ${SOCKET_ALLOWED_ORIGINS}
      MSAL_DOMAIN_NAME: ${MSAL_DOMAIN_NAME}
      MSAL_APP_CLIENT_ID: ${MSAL_APP_CLIENT_ID}
      MSAL_CLIENT_SECRET: ${MSAL_CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      SIGN_UP_SIGN_IN_FLOW: ${SIGN_UP_SIGN_IN_FLOW}
      POST_LOGOUT_REDIRECT_URI: ${POST_LOGOUT_REDIRECT_URI}

    # Overrides default command so things don't shut down after the process ends.
    command:
      - /bin/sh
      - -c
      - |
        git config --global --add safe.directory /app
        while sleep 1000; do :; done
